version: '3.4'

networks:
  dev:
    driver: bridge

services:
  glavni-shop: 
    image: docker.io/library/prvaverzija
    depends_on:
      - "app_db22"
    container_name: glavnishop-services
    ports:
      - "8089:81"
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ConnectionStrings__DefaultConnection=User ID=postgres;Password=postgres;Server=app_db22;Port=5432;Database=shopKnjigaDBGL;Pooling=true;
      - ASPNETCORE_URLS=http://+:80
    networks:
      - dev
  
  app_db22:
    image: postgres:latest
    container_name: app_db22
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=shopKnjigaDBGL
    ports:
      - "5490:5432"
    restart: always
    volumes:
      - app_data:/var/lib/postgresql/data
    networks:
      - dev
    
volumes:
  app_data: