// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShopKnjigaGlavni.DataAccess.Data;

#nullable disable

namespace ShopKnjigaGlavni.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240320165612_DodajProductKateogriju")]
    partial class DodajProductKateogriju
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ShopKnjigaGlavni.Models.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 1,
                            Name = "SciFi"
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 2,
                            Name = "Novel"
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 3,
                            Name = "Thriller"
                        });
                });

            modelBuilder.Entity("ShopKnjigaGlavni.Models.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ListPrice")
                        .HasColumnType("float");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<double>("Price100")
                        .HasColumnType("float");

                    b.Property<double>("Price50")
                        .HasColumnType("float");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Nez ko je",
                            CategoryId = 2,
                            Description = "Djecak koji zivi u snu",
                            ISBN = "aSDNJfjabaA",
                            ImageUrl = "https://th.bing.com/th/id/OIP.c2QKb4Z32HkDaKSSdojQHwHaF7?w=229&h=183&c=7&r=0&o=5&pid=1.7",
                            ListPrice = 15.0,
                            Price = 13.0,
                            Price100 = 7.0,
                            Price50 = 10.0,
                            Title = "Petar Pan"
                        },
                        new
                        {
                            Id = 2,
                            Author = "Rita Bullwinkel",
                            CategoryId = 2,
                            Description = "Zivot je borba",
                            ISBN = "agDNJfjfassaA",
                            ImageUrl = "https://th.bing.com/th/id/OIP.c2QKb4Z32HkDaKSSdojQHwHaF7?w=229&h=183&c=7&r=0&o=5&pid=1.7",
                            ListPrice = 18.0,
                            Price = 13.0,
                            Price100 = 10.0,
                            Price50 = 13.0,
                            Title = "Headshot"
                        },
                        new
                        {
                            Id = 3,
                            Author = "Tracy Sierra",
                            CategoryId = 2,
                            Description = "Gledanje mraka",
                            ISBN = "giasdbfajfaS",
                            ImageUrl = "https://th.bing.com/th/id/OIP.c2QKb4Z32HkDaKSSdojQHwHaF7?w=229&h=183&c=7&r=0&o=5&pid=1.7",
                            ListPrice = 20.0,
                            Price = 13.0,
                            Price100 = 7.0,
                            Price50 = 10.0,
                            Title = "Nightwatching"
                        });
                });

            modelBuilder.Entity("ShopKnjigaGlavni.Models.Models.Product", b =>
                {
                    b.HasOne("ShopKnjigaGlavni.Models.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
